/**
 * /api/search — Public search & filter endpoint
 *
 * Strategy:
 *  1. Try to fetch from the Kotlin backend (BUSINESS_SERVER_API_URL).
 *  2. If the backend is unreachable (dev mode, server down) fall back to
 *     the embedded mock data so the UI always renders.
 *
 * Filtering (category, location, query) is applied server-side here
 * since the Kotlin backend does not yet expose a search endpoint.
 */

import { NextResponse } from "next/server";
import { fetchAllBusinesses, filterBusinesses } from "@/lib/backend";

// ─── Embedded mock data (fallback only) ───────────────────────────────────
const MOCK_BUSINESSES = [
  {
    id: "dummy-business-0",
    name: "Lens & Light Studios",
    description:
      "Award-winning photography studio specialising in weddings, corporate events, and portrait sessions.",
    tagline: "Capturing your world, one frame at a time.",
    category: { id: "cat-0", categoryName: "Photography" },
    county: "Nairobi",
    subCounty: "Westlands",
    address: "14 Westlands Rd, Nairobi",
    contactEmail: "hello@lenslightstudios.co.ke",
    contactPhone: "+254 712 001 001",
    website: "https://lenslightstudios.co.ke",
    isManuallyOpen: true,
    status: "active",
    rating: "4.9",
    priceRange: "Ksh 5,000 - 50,000",
    availability: "Available Today",
    services: [
      { name: "Wedding Photography", price: "Ksh 25,000" },
      { name: "Portrait Session", price: "Ksh 5,000" },
    ],
    coverImage: null,
  },
  {
    id: "dummy-business-1",
    name: "Snapshot Collective",
    description:
      "Photography collective offering editorial, lifestyle, and product photography for brands.",
    tagline: "Visual stories that sell your brand.",
    category: { id: "cat-0", categoryName: "Photography" },
    county: "Nairobi",
    subCounty: "Karen",
    address: "5B Karen Shopping Centre",
    contactEmail: "studio@snapshotcollective.co.ke",
    contactPhone: "+254 700 112 233",
    website: null,
    isManuallyOpen: false,
    status: "active",
    rating: "4.7",
    priceRange: "Ksh 8,000 - 80,000",
    availability: "Available This Week",
    services: [{ name: "Product Photography", price: "Ksh 8,000" }],
    coverImage: null,
  },
  {
    id: "dummy-business-2",
    name: "Golden Hour Films",
    description:
      "Videography and photography duo serving Mombasa and the Coast region.",
    tagline: "The coast's favourite visual storytellers.",
    category: { id: "cat-0", categoryName: "Photography" },
    county: "Mombasa",
    subCounty: "Nyali",
    address: "Park Rd, Nyali, Mombasa",
    contactEmail: "info@goldenhourmsa.co.ke",
    contactPhone: "+254 722 334 455",
    website: "https://goldenhourmsa.co.ke",
    isManuallyOpen: true,
    status: "active",
    rating: "4.8",
    priceRange: "Ksh 15,000 - 100,000",
    availability: "Weekends Only",
    services: [{ name: "Destination Wedding Package", price: "Ksh 90,000" }],
    coverImage: null,
  },
  {
    id: "dummy-business-3",
    name: "AquaFix Kenya",
    description: "24/7 emergency plumbing services across Nairobi.",
    tagline: "Fast, reliable plumbing — any time of day.",
    category: { id: "cat-1", categoryName: "Plumbers" },
    county: "Nairobi",
    subCounty: "South B",
    address: "Mombasa Rd, South B",
    contactEmail: "support@aquafixkenya.co.ke",
    contactPhone: "+254 700 555 666",
    website: null,
    isManuallyOpen: true,
    status: "active",
    rating: "4.6",
    priceRange: "Ksh 500 - 10,000",
    availability: "Available Today",
    services: [{ name: "Emergency Call-out", price: "Ksh 1,500" }],
    coverImage: null,
  },
  {
    id: "dummy-business-4",
    name: "PipePro Services",
    description: "Experienced plumbers covering Kisumu and lakeside region.",
    tagline: "Your trusted pipe masters in Kisumu.",
    category: { id: "cat-1", categoryName: "Plumbers" },
    county: "Kisumu",
    subCounty: "Milimani",
    address: "Oginga Odinga Rd, Kisumu",
    contactEmail: "pipepro@gmail.com",
    contactPhone: "+254 733 667 788",
    website: null,
    isManuallyOpen: false,
    status: "active",
    rating: "4.4",
    priceRange: "Ksh 300 - 8,000",
    availability: "Available This Week",
    services: [{ name: "Pipe Repair", price: "Ksh 500" }],
    coverImage: null,
  },
  {
    id: "dummy-business-5",
    name: "Spark Solutions",
    description:
      "KPLC-certified electricians offering wiring, installations, and solar setups.",
    tagline: "Certified, safe, and on-time electrical work.",
    category: { id: "cat-2", categoryName: "Electricians" },
    county: "Nairobi",
    subCounty: "Industrial Area",
    address: "Enterprise Rd, Industrial Area",
    contactEmail: "info@sparksolutions.co.ke",
    contactPhone: "+254 722 778 899",
    website: "https://sparksolutions.co.ke",
    isManuallyOpen: true,
    status: "active",
    rating: "4.8",
    priceRange: "Ksh 1,000 - 50,000",
    availability: "Available Today",
    services: [
      { name: "House Wiring", price: "From Ksh 15,000" },
      { name: "Solar Panel Installation", price: "From Ksh 25,000" },
    ],
    coverImage: null,
  },
  {
    id: "dummy-business-6",
    name: "Volt Masters Nakuru",
    description:
      "Residential and industrial electrical contractors based in Nakuru.",
    tagline: "Powering homes and businesses in the Rift.",
    category: { id: "cat-2", categoryName: "Electricians" },
    county: "Nakuru",
    subCounty: "Nakuru Town",
    address: "Kenyatta Ave, Nakuru",
    contactEmail: "voltmasters@yahoo.com",
    contactPhone: "+254 711 223 344",
    website: null,
    isManuallyOpen: true,
    status: "active",
    rating: "4.5",
    priceRange: "Ksh 500 - 30,000",
    availability: "Available This Week",
    services: [{ name: "Socket Installation", price: "Ksh 500/socket" }],
    coverImage: null,
  },
  {
    id: "dummy-business-7",
    name: "ShineLine Cleaning Co.",
    description:
      "Professional home and office cleaning using eco-friendly products.",
    tagline: "Spotless spaces, happy people.",
    category: { id: "cat-3", categoryName: "Cleaning" },
    county: "Nairobi",
    subCounty: "Lavington",
    address: "Ring Rd, Lavington",
    contactEmail: "book@shinelinecleaning.co.ke",
    contactPhone: "+254 700 900 900",
    website: "https://shinelinecleaning.co.ke",
    isManuallyOpen: true,
    status: "active",
    rating: "4.7",
    priceRange: "Ksh 1,500 - 20,000",
    availability: "Available Today",
    services: [{ name: "Deep Clean", price: "Ksh 8,000" }],
    coverImage: null,
  },
  {
    id: "dummy-business-8",
    name: "Crystal Clean Mombasa",
    description:
      "Top-rated cleaning company for hotels, offices, and residences.",
    tagline: "We clean so you don't have to.",
    category: { id: "cat-3", categoryName: "Cleaning" },
    county: "Mombasa",
    subCounty: "Mombasa Island",
    address: "Nkrumah Rd, Mombasa",
    contactEmail: "info@crystalcleanmsa.co.ke",
    contactPhone: "+254 722 100 200",
    website: null,
    isManuallyOpen: false,
    status: "active",
    rating: "4.6",
    priceRange: "Ksh 2,000 - 30,000",
    availability: "Weekends Only",
    services: [{ name: "Post-Construction Clean", price: "From Ksh 10,000" }],
    coverImage: null,
  },
  {
    id: "dummy-business-9",
    name: "Torque Garage",
    description:
      "Full-service auto repair centre with OBD diagnostics and tyre services.",
    tagline: "Your car's best friend in Nairobi.",
    category: { id: "cat-4", categoryName: "Auto Repair" },
    county: "Nairobi",
    subCounty: "Ngong Road",
    address: "Ngong Rd, Nairobi",
    contactEmail: "torquegarage@gmail.com",
    contactPhone: "+254 711 556 677",
    website: null,
    isManuallyOpen: true,
    status: "active",
    rating: "4.5",
    priceRange: "Ksh 500 - 80,000",
    availability: "Available Today",
    services: [
      { name: "Full Service", price: "Ksh 4,500" },
      { name: "OBD Diagnostics", price: "Ksh 500" },
    ],
    coverImage: null,
  },
  {
    id: "dummy-business-10",
    name: "ProDrive Auto Centre",
    description:
      "Authorized service agents for Toyota and Nissan vehicles in Eldoret.",
    tagline: "Eldoret's number one auto care centre.",
    category: { id: "cat-4", categoryName: "Auto Repair" },
    county: "Eldoret",
    subCounty: "Langas",
    address: "Uganda Rd, Eldoret",
    contactEmail: "service@prodrive.co.ke",
    contactPhone: "+254 733 778 899",
    website: "https://prodrive.co.ke",
    isManuallyOpen: true,
    status: "active",
    rating: "4.7",
    priceRange: "Ksh 1,000 - 100,000",
    availability: "Available This Week",
    services: [{ name: "Toyota Service Schedule A", price: "Ksh 8,000" }],
    coverImage: null,
  },
  {
    id: "dummy-business-11",
    name: "Mama's Table Catering",
    description: "African cuisine catering for weddings and corporate events.",
    tagline: "Home-cooked flavours, event-scale service.",
    category: { id: "cat-5", categoryName: "Catering" },
    county: "Nairobi",
    subCounty: "Eastleigh",
    address: "Juja Rd, Eastleigh",
    contactEmail: "orders@mamastable.co.ke",
    contactPhone: "+254 700 111 222",
    website: null,
    isManuallyOpen: true,
    status: "active",
    rating: "4.9",
    priceRange: "Ksh 500 - 2,000 per head",
    availability: "Available This Week",
    services: [
      { name: "Wedding Package (200 pax)", price: "Ksh 300,000" },
      { name: "Corporate Lunch Box", price: "Ksh 600/head" },
    ],
    coverImage: null,
  },
  {
    id: "dummy-business-12",
    name: "Coastal Bites Catering",
    description:
      "Swahili and coastal cuisine specialists, fresh seafood and coconut rice.",
    tagline: "Taste the coast at your next event.",
    category: { id: "cat-5", categoryName: "Catering" },
    county: "Mombasa",
    subCounty: "Bamburi",
    address: "Bamburi Beach Rd, Mombasa",
    contactEmail: "sales@coastalbites.co.ke",
    contactPhone: "+254 722 445 556",
    website: "https://coastalbites.co.ke",
    isManuallyOpen: false,
    status: "active",
    rating: "4.8",
    priceRange: "Ksh 800 - 3,000 per head",
    availability: "Weekends Only",
    services: [{ name: "Seafood Buffet (per head)", price: "Ksh 1,800" }],
    coverImage: null,
  },
  {
    id: "dummy-business-13",
    name: "LifeCare Clinic",
    description:
      "General outpatient clinic with labs, pharmacy and vaccinations. NHIF accredited.",
    tagline: "Your health, our priority.",
    category: { id: "cat-6", categoryName: "Healthcare" },
    county: "Nairobi",
    subCounty: "Kasarani",
    address: "Thika Superhighway, Kasarani",
    contactEmail: "info@lifecareclinic.co.ke",
    contactPhone: "+254 700 333 444",
    website: "https://lifecareclinic.co.ke",
    isManuallyOpen: true,
    status: "active",
    rating: "4.5",
    priceRange: "Ksh 500 - 5,000",
    availability: "Available Today",
    services: [
      { name: "General Consultation", price: "Ksh 500" },
      { name: "Blood Test Panel", price: "Ksh 2,500" },
    ],
    coverImage: null,
  },
  {
    id: "dummy-business-14",
    name: "BrightMinds Tutoring",
    description:
      "Expert home and online tutoring for primary, secondary and A-level students.",
    tagline: "Unlocking potential, one student at a time.",
    category: { id: "cat-7", categoryName: "Education" },
    county: "Nairobi",
    subCounty: "Kilimani",
    address: "Argwings Kodhek Rd, Nairobi",
    contactEmail: "enrol@brightminds.co.ke",
    contactPhone: "+254 711 999 000",
    website: "https://brightminds.co.ke",
    isManuallyOpen: true,
    status: "active",
    rating: "4.9",
    priceRange: "Ksh 1,000 - 5,000/hr",
    availability: "Available This Week",
    services: [
      { name: "Primary (Std 1-8)", price: "Ksh 1,000/hr" },
      { name: "Secondary (Form 1-4)", price: "Ksh 2,000/hr" },
    ],
    coverImage: null,
  },
  {
    id: "dummy-business-15",
    name: "TechHub Kenya",
    description:
      "Electronics retail store — laptops, phones, accessories. Authorised Samsung dealer.",
    tagline: "Your go-to tech store in Nairobi.",
    category: { id: "cat-8", categoryName: "Retail" },
    county: "Nairobi",
    subCounty: "CBD",
    address: "Tom Mboya St, Nairobi CBD",
    contactEmail: "sales@techHub.co.ke",
    contactPhone: "+254 722 555 666",
    website: "https://techHub.co.ke",
    isManuallyOpen: true,
    status: "active",
    rating: "4.6",
    priceRange: "Ksh 500 - 200,000",
    availability: "Available Today",
    services: [
      { name: "Samsung Galaxy Series", price: "From Ksh 15,000" },
      { name: "Laptop Sales & Repair", price: "Varies" },
    ],
    coverImage: null,
  },
  {
    id: "dummy-business-16",
    name: "FashionForward Boutique",
    description:
      "Trendy women's wear, shoes, and accessories. New arrivals every week.",
    tagline: "Fashion that fits your life and budget.",
    category: { id: "cat-8", categoryName: "Retail" },
    county: "Kisumu",
    subCounty: "Kisumu CBD",
    address: "Oginga Odinga St, Kisumu",
    contactEmail: "shop@fashionforward.co.ke",
    contactPhone: "+254 700 445 556",
    website: null,
    isManuallyOpen: false,
    status: "active",
    rating: "4.4",
    priceRange: "Ksh 500 - 15,000",
    availability: "Available Today",
    services: [{ name: "Women's Dresses", price: "From Ksh 1,500" }],
    coverImage: null,
  },
  {
    id: "dummy-business-17",
    name: "GreenThumb Gardens",
    description:
      "Landscaping, lawn care, irrigation systems for estates and corporate campuses.",
    tagline: "Transforming outdoor spaces across Nairobi.",
    category: { id: "cat-9", categoryName: "Landscaping" },
    county: "Nairobi",
    subCounty: "Runda",
    address: "Runda Estate, Nairobi",
    contactEmail: "info@greenthumbgardens.co.ke",
    contactPhone: "+254 733 112 223",
    website: "https://greenthumbgardens.co.ke",
    isManuallyOpen: true,
    status: "active",
    rating: "4.8",
    priceRange: "Ksh 5,000 - 150,000",
    availability: "Available This Week",
    services: [
      { name: "Monthly Lawn Maintenance", price: "From Ksh 5,000" },
      { name: "Full Garden Design", price: "From Ksh 80,000" },
    ],
    coverImage: null,
  },
  {
    id: "dummy-business-18",
    name: "Fine Joints Carpentry",
    description:
      "Custom furniture makers — kitchens, wardrobes, beds, and office fit-outs.",
    tagline: "Handcrafted furniture built to last.",
    category: { id: "cat-10", categoryName: "Carpenters" },
    county: "Nairobi",
    subCounty: "Githurai",
    address: "Thika Rd, Githurai 45",
    contactEmail: "orders@finejoints.co.ke",
    contactPhone: "+254 711 334 445",
    website: null,
    isManuallyOpen: true,
    status: "active",
    rating: "4.7",
    priceRange: "Ksh 5,000 - 200,000",
    availability: "Available This Week",
    services: [
      { name: "Kitchen Cabinet Set", price: "From Ksh 80,000" },
      { name: "3-door Wardrobe", price: "From Ksh 25,000" },
    ],
    coverImage: null,
  },
  {
    id: "dummy-business-19",
    name: "Timber Works Nakuru",
    description:
      "Carpenters handling door frames, window fitting, roofing timber, and interior woodwork.",
    tagline: "Solid craftsmanship you can trust.",
    category: { id: "cat-10", categoryName: "Carpenters" },
    county: "Nakuru",
    subCounty: "Pandit",
    address: "Kenyatta Ave, Nakuru",
    contactEmail: "timberworks@gmail.com",
    contactPhone: "+254 700 667 778",
    website: null,
    isManuallyOpen: false,
    status: "active",
    rating: "4.3",
    priceRange: "Ksh 2,000 - 50,000",
    availability: "Weekends Only",
    services: [{ name: "Door Frame Fitting", price: "Ksh 2,500" }],
    coverImage: null,
  },
];

// ─── Route handler ─────────────────────────────────────────────────────────

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const category = searchParams.get("category") ?? undefined;
  const q = searchParams.get("q") ?? undefined;
  const location = searchParams.get("location") ?? undefined;

  let businesses: any[] = [];
  let source: "backend" | "mock" = "backend";

  // 1. Try the Kotlin backend
  try {
    businesses = await fetchAllBusinesses(0, 200);
  } catch (err: any) {
    console.warn(
      `[search] Kotlin backend unavailable (${err?.message ?? err}). Using mock data.`,
    );
    businesses = MOCK_BUSINESSES as any[];
    source = "mock";
  }

  // 2. Apply filters
  businesses = filterBusinesses(businesses, { query: q, category, location });

  return NextResponse.json({
    businesses,
    total: businesses.length,
    source,
  });
}
